config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 105}, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
      if @article.update(article_params)
        flash[:notice] = "Article was successfully updated"
        redirect_to article_path(@article)
      else
        render 'edit'
      end
  end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article was successfully deleted.'
      redirect_to articles_path
    end
  end
  
  
  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # byebug
    user = User.find_by(email: params[:session][:email].downcase) #
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user # user_path(user)
    else
      flash.now[:alert] = "There is something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.all
  end
  
  
  def show
    @articles = @user.articles
  end
  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
      else
        render 'edit'
      end
  end

  def destroy
    if current_user == @user
      session[:user_id] = nil
    end
    @user.destroy
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end
  

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end  

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/views/articles/_article.html.erb
<div id="demo" class="carousel slide" data-bs-ride="carousel">

  <div class="carousel-indicators justify-content-center">
    <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
    <% (1..@articles.length - 1).each do |i| %>
      <% if i%3 == 0 %>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="<%= i/3 %>"></button>
      <% end %>
    <% end %>
  </div>
  
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="d-flex flex-row">
        <% @articles.first(3).each_with_index do |article, index| %>
            <div class="card" onclick="flip(event)">
              <div class="card-body front">
                <h2>0<%= index + 1 %></h2>
                <h3><%= article.title %></h3>
                <p class="text-white"><%= article.description %></p>
                <footer><small>Article written by <%= article.user.username if article.user %></small></footer>
              </div>
              <div class="card-body back">
                <div class="card-btn">
                  <%= link_to "View", article_path(article) %>
                </div>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                  <div class="card-btn">
                    <%= link_to "Edit", edit_article_path(article) %>
                  </div>
                  <div class="card-btn">
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <% if @articles.length > 3 %>
      <% (1..@articles.length/3).each do |ofst|%>
        <div class="carousel-item">
          <div class="d-flex flex-row">
            <% @articles.limit(3).offset(ofst*3).each_with_index do |article, index| %>
              <div class="card" onclick="flip(event)">
                <div class="card-body front">
                  <h2>0<%= ofst * 3 + index + 1 %></h2>
                  <h3><%= article.title %></h3>
                  <p class="text-white"><%= article.description %></p>
                  <footer><small>Article written by <%= article.user.username %></small></footer>
                </div>
              <div class="card-body back">
                <div class="card-btn">
                  <%= link_to "View", article_path(article) %>
                </div>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                  <div class="card-btn">
                    <%= link_to "Edit", edit_article_path(article) %>
                  </div>
                  <div class="card-btn">
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                <% end %>
              </div> 
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
function flip(event){
	var element = event.currentTarget;
  front = element.childNodes[1];
  back = element.childNodes[3];
	if (element.className === "card") {
    if(element.style.transform == "rotateY(360deg)") {
      element.style.transform = "rotateY(0deg)";
      back.style.display = "none";
      front.style.display = "block";
    }
    else {
      element.style.transform = "rotateY(360deg)";
      front.style.display = "none";
      back.style.display = "block";

    }
  }
};
</script>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<%= form_with(model: @article, local: true) do |f| %>
<div class="login-form">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="form-group h5">
          <%= f.label :title, class: "row col-2 col-form-label text-light" %>
          <div class="row col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group h5 mt-4">
          <%= f.label :description, class: "row col-2 col-form-label text-light" %>
          <div class="row col-10"> 
            <%= f.text_area :description, rows: 8, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="btn btn-success place-center">
  <a><%= f.submit id: "id", class: "text-white" %></a>
</div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<%= render "article" %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="login-form justify-content-center" data-tilt>
    <div class="container text-white text-center">
        <div class="row">
            <h1 class="display-4"><%= @article.title %></h1>
        </div>
        <p class="lead"><%= @article.description %></p>
    </div>
</div>

<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  <div class="container">
    <div class="row">
      <div class="col-3">
      </div>
      <div class="col-3 justify-content-center">
        <div class="btn btn-success">
          <%= link_to "Edit", edit_article_path(@article) %>
        </div>
      </div>
      <div class="col-2">
        <div class="btn">
          <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="py-4">
    <section>
        <ul>
            <li>
                <%= link_to '<i class="fa fa-twitter"></i>'.html_safe, "https://twitter.com/_manish1017?t=vioAhkGezzxOacA5fxqXUQ&s=08" %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-github"></i>'.html_safe, "https://github.com/manishkumarr1017" %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-briefcase"></i>'.html_safe, "https://manish-kumarr.web.app/" %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-facebook">'.html_safe, "https://m.facebook.com/100013918269506/" %></i>
            </li>
            <li>
                <%= link_to '<i class="fa fa-linkedin"></i>'.html_safe, "https://in.linkedin.com/in/manish-kumar-8bab07210" %>
            </li>
        </ul>
    </section>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>  
  <% if name == "notice" %>
    <div class="alert alert_success">
      <span class="icon">
          <i class="fa fa-check"></i>
      </span>

      <div class="text">
          <strong>Success</strong>
          <p><%= msg %></p>
      </div>
      <button class="close">
          <i class="fa fa-close"></i>
      </button>
    </div>
  <% else %>
    <div class="alert alert_danger">
      <span class="icon">
        <i class="fa fa-close"></i>
      </span>
  
      <div class="text">
        <strong>Danger</strong>
        <p><%= msg %></p>
      </div>
  
      <button class="close">
        <i class="fa fa-close"></i>
      </button>
    </div>
  <% end %>
<% end %> 

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="slide">
    <nav>
      <span>
        <%= link_to "Home", root_path %>
        <%= link_to "Articles", articles_path %>
        <%= link_to "Blogger", users_path %>
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: :delete %>
        <% else %>
          <%= link_to "Login", login_path %>
        <% end %>
      </span>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/messages' %>
    <div class="container row">
      <%= render 'layouts/navigation' %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_pack_tag 'custom', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron justify-content-center" data-tilt>
    <div class="container text-white text-center">
        <div class="row">
            <h1 class="display-4">Alpha Blog</h1>
        </div>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <% if logged_in? %>
            <div class="card-btn">
                <%= link_to  new_article_path do %>
                    Create New<br>Article
                <% end %>
            </div>
            <div class="flex">
                <div class="card-btn">
                    <%= link_to  current_user do %>
                        View<br>Articles
                    <% end %>
                </div>
                <div class="card-btn">
                    <%= link_to edit_user_path(current_user) do %>
                        Edit<br>Profile
                    <% end %>
                </div>
                <div class="card-btn">
                <%= link_to user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } do %>
                        Delete<br>Profile
                    <% end %>
                </div>
            </div>
        <% else %>
            <div class="card-btn">
                <%= link_to "Sign up!", signup_path %>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |msg| %>
    <div class="alert alert_warning">
      <span class="icon">
          <i class="fa fa-exclamation-triangle"></i>
      </span>

      <div class="text">
          <strong>Warning</strong>
            <p><%= msg %></p>
      </div>
      <button class="close">
          <i class="fa fa-close"></i>
      </button>
    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_with(model: @user, local: true) do |f| %>

<div class="login-form login-form-sm">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="form-group h5">
          <%= f.label :username, class: "row col-2 col-form-label text-light" %>
          <div class="row col-12">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter your username" %>
          </div>
        </div>
        <div class="form-group h5 mt-4">
          <%= f.label :email, class: "row col-2 col-form-label text-light" %>
          <div class="row col-12"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email" %>
          </div>
        </div>
        <div class="form-group h5 mt-4">
          <%= f.label :password, class: "row col-2 col-form-label text-light" %>
          <div class="row col-12"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="btn btn-primary place-center">
  <a><%= f.submit(@user.new_record? ? "Sign up!" : "Update", id: "id", class: "text-white")%></a>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div id="demo" class="carousel slide" data-bs-ride="carousel">

  <div class="carousel-indicators justify-content-center">
    <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
    <% (1..@users.length - 1).each do |i| %>
      <% if i%3 == 0 %>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="<%= i/3 %>"></button>
      <% end %>
    <% end %>
  </div>
  
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="d-flex flex-row">
        <% @users.first(3).each_with_index do |user, index| %>
            <div class="card" onclick="flip(event)">
              <div class="card-body front">
                <h2>0<%= index + 1 %></h2>
                <%= image_tag "manish.jpeg", height: 150, class: "rounded shadow mt-4", alt: user.username %>
                <h3 class="mt-4"><%= user.username.upcase %></h3>
                <div class="card-btn">
                  <%= link_to "View Articles", user %>
                </div>
                <small class="text-white">Joined <%= time_ago_in_words(user.created_at) %> ago</small>
              </div>
              <div class="card-body back">
                <div class="card-btn">
                  <%= link_to "View", user %>
                </div>
                <% if logged_in? && (user == current_user || current_user.admin?) %>
                  <div class="card-btn">
                    <%= link_to "Edit", edit_user_path(user) %>
                  </div>
                  <div class="card-btn">
                    <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
                  </div>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
    <% if @users.length > 3 %>
      <% (1..@users.length/3).each do |ofst|%>
        <div class="carousel-item">
          <div class="d-flex flex-row">
            <% @users.limit(3).offset(ofst*3).each_with_index do |user, index| %>
              <div class="card" onclick="flip(event)">
                <div class="card-body front">
                  <h2>0<%= ofst * 3 + index + 1 %></h2>
                  <%= image_tag "manish.jpeg", height: 150, class: "rounded shadow mt-4", alt: user.username %>
                  <h3 class="mt-4"><%= user.username.upcase %></h3>
                  <div class="card-btn">
                    <%= link_to "View Articles", user %>
                  </div>
                  <small class="text-white">Joined <%= time_ago_in_words(user.created_at) %> ago</small>
                </div>
                <div class="card-body back">
                  <div class="card-btn">
                    <%= link_to "View", user %>
                  </div>
                  <% if logged_in? && (current_user == user || current_user.admin?) %>
                    <div class="card-btn">
                      <%= link_to "Edit", edit_user_path(user) %>
                    </div>
                    <div class="card-btn">
                      <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
function flip(event){
	var element = event.currentTarget;
  front = element.childNodes[1];
  back = element.childNodes[3];
	if (element.className === "card") {
    if(element.style.transform == "rotateY(360deg)") {
      element.style.transform = "rotateY(0deg)";
      back.style.display = "none";
      front.style.display = "block";
    }
    else {
      element.style.transform = "rotateY(360deg)";
      front.style.display = "none";
      back.style.display = "block";

    }
  }
};
</script>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<%= render "articles/article" %>